# Chest Commands by Filoghost
# Tutorial: dev.bukkit.org/bukkit-plugins/chest-commands
#                                                       .
update-notifications: false
try-to-hide-attributes: true
default-item-name-color: '&f'
default-lore-color: '&7'
messages:
  not-enough-money: '&cYou don''t have enough money (&e<price>&c) for this command.'
  no-item-permission: '&cTo use this item you need the permission &e<permission>&c.'
  no-required-item: '&cYou must have &e<amount>x <material> &c(ID: <id>, data value:
    <datavalue>) for this.'
