caidan:
  location: world, 821.617, 5.997, -143.609
  lines:
  - '&u全服快捷菜单'
  - '&b输入/cd 即可打开传送快捷菜单'
  - '&u前方为10-30级中低级副本'
  - '&e&n输入/赞助 即可打开点券商城'
  - '&4【网站输入提示】请注意大小写，否则打开没有商品'
  - '&a赞助网址:&b&l&nhttp://www.mcrmb.com/cz/4445'
jingyan:
  location: world, 810.253, 6.621, -143.178
  lines:
  - '&6本服升级等级全靠剧情主线任务'
  - '&3BOOS和精英怪物也会掉落一定的经验'
  - '&5但建议还是靠做任务获得经验'
