#声望果实物品信息
Item:
  #物品名称
  Name: '&e灵晶'
  #物品ID
  ID: 264
  #物品Lore
  Lore:
    - '&a可增加100点段位值'
    - '&e右键使用'
#声望果实增加声望值
FameItemAdd: 100
#玩家初始声望值
DefaultFame: 30
#杀敌次数清除间隔
#例如清除时间为10秒
#玩家在10秒内击杀2个玩家即双杀
#然后刷新间隔
#又在10秒内击杀第三个则是三杀
#间隔数值为毫秒
#1秒=1000毫秒
ClearTime: 10000
#杀敌获得声望
KillFame: 5
#死亡减少经验
DeathExp: 10
#多次杀敌的额外声望
#当杀敌次数在配置文件中没有并大于最大值将会获得最大值的声望
KillMoreFame:
  '2': 5
  '3': 10
  '4': 15
  '5': 20
#当玩家有101声望时也有屠夫称号,直到110有新称号时才会更新
Prefixs:
  #名称,随意
  'a':
    #所需声望
    Fame: 0
    #前缀
    Prefix: ''
  'b':
    Fame: 100
    Prefix: '&a[青铜1段]'
  'c':
    Fame: 200
    Prefix: '&a[青铜2段]'
  '1':
    Fame: 400
    Prefix: '&a[青铜3段]'
  '2':
    Fame: 600
    Prefix: '&e[青铜4段]'
  '3':
    Fame: 1000
    Prefix: '&e[青铜5段]'
  '4':
    Fame: 1500
    Prefix: '&e[白银1段]'
  '5':
    Fame: 2000
    Prefix: '&9[白银2段]'
  '6':
    Fame: 2500
    Prefix: '&9[白银3段]'
  '7':
    Fame: 3000
    Prefix: '&9[白银4段]'
  '8':
    Fame: 3500
    Prefix: '&5[白银5段]'
  '9':
    Fame: 4500
    Prefix: '&5[黄金1段]'
  'e':
    Fame: 5500
    Prefix: '&5[黄金2段]'
  'f':
    Fame: 6500
    Prefix: '&c[黄金3段]'
  'g':
    Fame: 7500
    Prefix: '&4[黄金4段]'
  'o':
    Fame: 10000
    Prefix: '&c[黄金5段]'
  'p':
    Fame: 15000
    Prefix: '&c[钻石1段]'
  'q':
    Fame: 20000
    Prefix: '&c[钻石2段]'
  'r':
    Fame: 30000
    Prefix: '&5[钻石3段]'
  's':
    Fame: 40000
    Prefix: '&5[钻石4段]'
  't':
    Fame: 50000
    Prefix: '&b[钻石5段]'
  'z':
    Fame: 70000
    Prefix: '&a[&e至&b尊&5段&4]'
  'x':
    Fame: 100000
    Prefix: '&b[&a泰&6拉&5石&c]'
