# Default config for ItemLoreStats.

fileVersion: 582
serverVersion: 1710
checkForUpdates: false
languageFile: language-en
usingMcMMO: false
usingBarAPI: true
usingBossBarAPI: true
dropCustomILSLoot: false
ILSLootFromNaturalSpawnsOnly: false
addSellValueToDrops: true
enableItemRepairing: true
keepXPOnDeath: true
addRandomLore: false
randomApplyChance: 45
baseHealth: 20
baseHealthRegen: 2
baseMovementSpeed: 0.2
baseCritDamage: 30
healthScale: 20
levelCap: 9999
displayDurabilityWarnings:
  enable75%DurabilityWarning: true
  enable50%DurabilityWarning: true
  enable25%DurabilityWarning: true
disabledInWorlds:
- worldNEW
messages:
  loreSuccessfullyAdded: true
  upgradeSuccessful: true
  upgradeCapReached: true
  itemReceived: true
  itemLooted: true
vanilla:
  includeDamage: true
  includeArmour: false
combatMessages:
  outgoing:
    damageDone: false
    enemyDodgedAttack: true
    enemyBlockedAttack: true
    critStrike: true
    lifeSteal: true
    enemyReflectedAttack: true
    fire: true
    ice: true
    poison: true
    wither: true
    harm: true
    blind: true
  incoming:
    damageTaken: false
    dodgeAttack: true
    blockAttack: true
    enemyCritStrike: false
    enemyLifeSteal: false
    reflectAttack: false
    enemyFire: false
    enemyIce: false
    enemyPoison: false
    enemyWither: false
    enemyHarm: false
    enemyBlind: false
prefix:
  random:
  - 天使
  - 残酷
  - 诅咒
  - 授权
  - 精良
  - 闪光
  - 沉重
  - 完美
  - 锋利
  - 标准
  - 磨损
  - 燃烧
  - 优雅
  - 光滑
  - 坚硬
  - 厚实
  - 冷酷
suffix:
  random:
  - 的混乱
  - 的破坏
  - 的杀戮
  - 的力量
  - 的沉默
  - 的悲哀
  - 的恐惧
  - 的雷鸣
  - 的古老
  - 的黑暗
  - 的荒野
randomLore:
  tools:
    bow:
    - '&c使用古老的树枝精心制作完成.'
    - '&a这个{item}受到了时间的腐蚀, 但是依然强力.'
    - '&9这个{item}是一个轻量级装备, 便于携带.'
    stick:
    - '&c使用古老的树枝精心制作完成.'
    - '&a这个{item}受到了时间的腐蚀, 但是依然强力.'
    - '&9这个{item}是一个轻量级装备, 便于携带.'
    blazeRod:
    - '&c使用永恒之火精心制作完成.'
    - '&a这个{item}受到了时间的腐蚀, 但是依然强力.'
    - '&9这个{item}是一个轻量级装备, 便于携带.'
    string:
    - '&a这个{item}受到了时间的腐蚀, 但是依然强力.'
    - '&9这个{item}是一个轻量级装备, 便于携带.'
    shears:
    - '&9这个{item}是一个轻量级装备, 便于携带.'
    wood:
    - '&c使用古老的树枝精心制作完成.'
    - '&a这个{item}受到了时间的腐蚀, 但是依然强力.'
    - '&9这个{item}是一个轻量级装备, 便于携带.'
    stone:
    - '&c这个{item}为当地的制作材料.'
    - '&a这个{item}是非常强硬的.'
    - '&9这个{item}最初比现在还要锐利.'
    iron:
    - '&c这个{item}能够制作非常坚硬的刀片.'
    - '&a这个{item}有点生锈了.'
    - '&9这个{item}是由最有名的铁匠锻造而成.'
    gold:
    - '&c非常昂贵的材料.'
    - '&a每个国王都非常喜欢使用它.'
    - '&9使用{item}制作的武器都非常的弱.'
    diamond:
    - '&c非常值钱而又坚硬的材料.'
    - '&a仅有少数人得到过这种材料.'
    - '&9这个{item}能够制作非常强力的武器.'
  armour:
    leather:
    - '&c由马的皮制作而成的装备.'
    - '&a由牛的皮制作而成的装备.'
    - '&9这个{item}是轻量级的装备, 但是提供了有效的保护.'
    iron:
    - '&c这个{item}提供了较好的保护.'
    - '&a这个{item}比较强力.'
    - '&9这个{item}是由有名的铁匠锻造而成.'
    gold:
    - '&c这个{item}提供了良好的保护.'
    - '&a昂贵的材料精心制作完成.'
    - '&9这个{item}的耐久不是很强.'
    diamond:
    - '&c这个{item}提供了强大的保护'
    - '&a使用最好的材料精心制作完成'
    - '&9这个{item}是非常强大的.'
    mobHead:
    - '&c斩首!!!'
primaryStats:
  armour:
    name: 防御力
    colour: '&3'
    sellValuePerStat: 12
    prefix:
      colour: '&3'
      list:
      - Shielded
    suffix:
      colour: '&3'
      list:
      - of Protection
  damage:
    name: 攻击力
    colour: '&3'
    sellValuePerStat: 0.9
  health:
    name: 生命
    colour: '&3'
    sellValuePerStat: 0.7
  healthRegen:
    name: 生命回复
    colour: '&3'
    sellValuePerStat: 12
    prefix:
      colour: '&3'
      list:
      - Regenerating
    suffix:
      colour: '&3'
      list:
      - of Regeneration
secondaryStats:
  block:
    name: 格挡
    colour: '&3'
    sellValuePerStat: 6
    internalCooldown: 3
    prefix:
      colour: '&3'
      list:
      - Impeding
    suffix:
      colour: '&3'
      list:
      - of the Blockade
  dodge:
    name: 闪避
    colour: '&3'
    sellValuePerStat: 9
    internalCooldown: 3
    prefix:
      colour: '&3'
      list:
      - Eluding
    suffix:
      colour: '&3'
      list:
      - of Evasion
  critChance:
    name: 暴击几率
    colour: '&3'
    sellValuePerStat: 9
    internalCooldown: 3
    prefix:
      colour: '&3'
      list:
      - Lethal
    suffix:
      colour: '&3'
      list:
      - of Deep Wounds
  critDamage:
    name: 暴击伤害
    colour: '&3'
    sellValuePerStat: 7
    prefix:
      colour: '&3'
      list:
      - Lethal
    suffix:
      colour: '&3'
      list:
      - of Deep Wounds
  lifeSteal:
    name: 嗜血
    colour: '&a'
    sellValuePerStat: 5
    internalCooldown: 3
    prefix:
      colour: '&a'
      list:
      - Life Stealing
    suffix:
      colour: '&a'
      list:
      - of Soul Draining
    healPercentage: 0.15
  reflect:
    name: 伤害反弹
    colour: '&e'
    sellValuePerStat: 6
    internalCooldown: 3
    prefix:
      colour: '&e'
      list:
      - Reflecting
    suffix:
      colour: '&e'
      list:
      - of Reflection
  fire:
    name: 烈焰攻击
    colour: '&c'
    sellValuePerStat: 9
    internalCooldown: 3
    effectDuration: 3
    prefix:
      colour: '&c'
      list:
      - Flaming
    suffix:
      colour: '&c'
      list:
      - of the Inferno
  ice:
    name: 寒冰攻击
    colour: '&9'
    sellValuePerStat: 7
    internalCooldown: 3
    effectDuration: 3
    effectAmplifier: 1
    prefix:
      colour: '&9'
      list:
      - Freezing
    suffix:
      colour: '&9'
      list:
      - of the Blizzard
  poison:
    name: 剧毒攻击
    colour: '&2'
    sellValuePerStat: 8
    internalCooldown: 3
    effectDuration: 3
    effectAmplifier: 1
    prefix:
      colour: '&2'
      list:
      - Toxic
    suffix:
      colour: '&2'
      list:
      - of Poison
  wither:
    name: 凋零攻击
    colour: '&f'
    sellValuePerStat: 9
    internalCooldown: 3
    effectDuration: 3
    effectAmplifier: 1
    prefix:
      colour: '&f'
      list:
      - Corrupted
    suffix:
      colour: '&f'
      list:
      - of Corruption
  harming:
    name: 伤害攻击
    colour: '&5'
    sellValuePerStat: 4
    internalCooldown: 3
    effectDuration: 3
    effectAmplifier: 1
    prefix:
      colour: '&5'
      list:
      - Crippling
    suffix:
      colour: '&5'
      list:
      - of Harming
  blind:
    name: 致盲攻击
    colour: '&7'
    sellValuePerStat: 10
    internalCooldown: 3
    effectDuration: 3
    effectAmplifier: 1
    prefix:
      colour: '&7'
      list:
      - Visionless
    suffix:
      colour: '&7'
      list:
      - of Blinding
  movementSpeed:
    name: 速度提升
    colour: '&6'
    sellValuePerStat: 4
    internalCooldown: 3
    prefix:
      colour: '&6'
      list:
      - Swift
    suffix:
      colour: '&6'
      list:
      - of Swiftness
bonusStats:
  pvpDamage:
    name: PvP额外伤害
    colour: '&6'
    sellValuePerStat: 1.5
  pveDamage:
    name: PvE额外伤害
    colour: '&2'
    sellValuePerStat: 1.5
  xpLevel:
    name: 等级
    colour: '&3'
    sellValuePerStat: 10
  xpMultiplier:
    name: 经验加成
    colour: '&d'
    sellValuePerStat: 8
    prefix:
      colour: '&d'
      list:
      - Premium
    suffix:
      colour: '&d'
      list:
      - of Rewarding
  soulbound:
    name: 绑定玩家
    colour: '&3'
    sellValuePerStat: 0
  weaponSpeed:
    name: 攻击速度
    colour: '&b'
    sellValuePerStat:
      veryFast: 25
      fast: 20
      normal: 15
      slow: 10
      verySlow: 5
  durability:
    name: 耐久度
    colour: '&8'
    sellValuePerStat: 0
    splitter: /
  setBonus:
    name: 设置奖金
    colour: '&6'
    sellValuePerStat: 0
  class:
    name: 职业
    colour: '&3'
    sellValuePerStat: 0
    separator: ','
    list:
    - '&f血红恶魔'
    - '&f流浪剑客'
    - '&f兽族狂斧'
    - '&f狩猎游侠'
    - '&f长棍武僧'
  sellValue:
    name: 出售价格
    colour: '&7'
    currency:
      name: 硬币
      colour: '&f'
heroesOnlyStats:
  heroesMaxMana:
    enabled: true
    name: 法力
    colour: '&3'
    sellValuePerStat: 2
spells:
  tnt:
    name: 炸弹爆破
    colour: '&c'
    sellValuePerStat: 25
    cooldown: 15
    detonationTime: 5
    speed: 3
  fireball:
    name: 烈焰之球
    colour: '&6'
    sellValuePerStat: 25
    cooldown: 15
    speed: 3
  lightning:
    name: 极地闪电
    colour: '&9'
    sellValuePerStat: 25
    cooldown: 15
  frostbolt:
    name: 冰霜之球
    colour: '&b'
    sellValuePerStat: 25
    cooldown: 15
    speed: 3
  minorHeal:
    name: 低级治疗术
    colour: '&a'
    sellValuePerStat: 25
    cooldown: 30
    healAmount: 15
  majorHeal:
    name: 高级治疗术
    colour: '&2'
    sellValuePerStat: 25
    cooldown: 60
    healAmount: 35
  minorAOEHeal:
    name: 低级群体治疗术
    colour: '&d'
    sellValuePerStat: 25
    cooldown: 45
    healAmount: 10
  majorAOEHeal:
    name: 高级群体治疗术
    colour: '&5'
    sellValuePerStat: 25
    cooldown: 90
    healAmount: 30
bossBar:
  splitter: ' | '
  colour: '&7'
  health:
    name: 生命值
    colour: '&a'
    splitter: /
  level:
    enabled: true
    name: 等级
    colour: '&e'
  exp:
    enabled: true
    name: 经验
    colour: '&b'
    splitter: /
upgradeStatsOnLevelChange:
  enabled: false
  upgradeCap: 5
  stats:
    armour: 0.1
    dodge: 0.1
    block: 0.1
    critChance: 0.2
    critDamage: 0.3
    damage: 0.1
    health: 0.3
    healthRegen: 0.1
    lifeSteal: 0.2
    reflect: 0.1
    fire: 0.1
    ice: 0.1
    poison: 0.1
    wither: 0.1
    harming: 0.1
    blind: 0.1
    movementSpeed: 0.5
    xpMultiplier: 0.1
    pvpDamage: 0.3
    pveDamage: 0.3
    heroesMaxMana: 0.2
    healthregen: 0.12
    lifesteal: 0.16
    movementspeed: 0.47
    xpmultiplier: 0.09
    pvpdamage: 0.3
    pvedamage: 0.3
environmentalDamage:
  block_explosion:
    damage: 20
    durabilityLost: 0
  cactus:
    damage: 5
    durabilityLost: 0
  drowning:
    damage: 10
    durabilityLost: 0
  entity_explosion:
    damage: 20
    durabilityLost: 0
  fall:
    damage: 12
    durabilityLost: 0
  fire:
    damage: 5
    durabilityLost: 0
  fire_tick:
    damage: 5
    durabilityLost: 0
  lava:
    damage: 20
    durabilityLost: 0
  lightning:
    damage: 10
    durabilityLost: 0
  magic:
    damage: 5
    durabilityLost: 0
  poison:
    damage: 5
    durabilityLost: 0
  starvation:
    damage: 5
    durabilityLost: 0
  suffocation:
    damage: 5
    durabilityLost: 0
  thorns:
    damage: 2
    durabilityLost: 0
  damage:
    durabilityLost: 0
potions:
  instantHealthI: 15
  instantHealthII: 35
  splashHealthI: 15
  splashHealthII: 35
additionalStatsPerLevel:
  health: 0
  healthRegen: 0.004
  speed: 0
defaultCraftedDurability:
  enableDurabilityOnCrafted: true
  enableDurabilityOnDrops: false
  tools:
    bow: '&1-1'
    shears: '&1-1'
    stick: '&1-1'
    string: '&1-2'
    blazeRod: '&1-2'
    flintAndSteel: '&1-2'
    fishingRod: '&1-2'
    carrotStick: '&1-2'
    wood: '&1-2'
    stone: '&1-2'
    iron: '&1-2'
    gold: '&2-1'
    diamond: '&1-2'
  armour:
    leather: '&1-2'
    iron: '&1-2'
    chainmail: '&1-2'
    gold: '&1-2'
    diamond: '&1-2'
    mobHead: '&&1-2'
defaultCraftedArmour:
  enableArmourOnCrafted: true
  enableArmourOnDrops: true
  armourStatFormat: '&3[statName]: &b[statValue]&3%'
  armour:
    leather: '&b3.6-7.3'
    iron: '&b7.8-15.6'
    chainmail: '&b6.2-12.5'
    gold: '&b5.7-11.4'
    diamond: '&b10.4-20.8'
    mobHead: '&b4.0-15.0'
defaultCraftedDamage:
  enableDamageOnCrafted: true
  enableDamageOnDrops: true
  damageStatFormat: '&3[statName]: +&b[statValue]-[statValue2]'
  tool:
    bow: '&b3.6-7.3'
    wood: '&b7.8-15.6'
    stone: '&b6.2-12.5'
    iron: '&b5.7-11.4'
    gold: '&b10.4-20.8'
    diamond: '&b4.1-15.5'
durabilityAddedOnEachRepair:
  repairCostType: Material
  repairBlock: WORKBENCH
  tools:
    bow: 75
    shears: 35
    flintAndSteel: 15
    fishingRod: 15
    carrotStick: 13
    wood: 75
    stone: 125
    iron: 150
    gold: 275
    diamond: 350
  armour:
    leather: 650
    iron: 850
    chainmail: 1000
    gold: 1100
    diamond: 1200
  repairCurrencyCost:
    tools:
      bow: 50
      shears: 80
      flintAndSteel: 75
      fishingRod: 45
      carrotStick: 70
      wood: 60
      stone: 100
      iron: 135
      gold: 150
      diamond: 200
    armour:
      leather: 120
      iron: 270
      chainmail: 290
      gold: 300
      diamond: 400
materialSellValue:
  tools:
    bow: 30
    shears: 15
    flintAndSteel: 10
    fishingRod: 10
    carrotStick: 15
    wood:
      sword: 35
      axe: 25
      hoe: 15
      pickaxe: 15
      spade: 20
    stone:
      sword: 55
      axe: 45
      hoe: 35
      pickaxe: 35
      spade: 40
    iron:
      sword: 75
      axe: 65
      hoe: 55
      pickaxe: 55
      spade: 60
    gold:
      sword: 95
      axe: 85
      hoe: 75
      pickaxe: 75
      spade: 80
    diamond:
      sword: 115
      axe: 105
      hoe: 95
      pickaxe: 95
      spade: 100
  armour:
    leather:
      helmet: 35
      chestplate: 25
      leggings: 15
      boots: 15
    iron:
      helmet: 75
      chestplate: 65
      leggings: 55
      boots: 55
    chainmail:
      helmet: 55
      chestplate: 45
      leggings: 35
      boots: 35
    gold:
      helmet: 95
      chestplate: 85
      leggings: 75
      boots: 75
    diamond:
      helmet: 115
      chestplate: 105
      leggings: 95
      boots: 95
    mobHead: 100
enchants:
  sharpness:
    levelMultiplier: 5
  unbreaking:
    levelMultiplier: 33
  power:
    levelMultiplier: 5
  featherFalling:
    levelMultiplier: 10
npcDropEquippedGear:
  dropChance:
    helmet: 0
    chestplate: 0
    leggings: 0
    boots: 0
    itemInHand: 0
materials:
  tools:
  - BLAZE_ROD
  - BOW
  - BUCKET
  - CARROT_STICK
  - FISHING_ROD
  - FLINT_AND_STEEL
  - SHEARS
  - STICK
  - STRING
  - WOOD_SWORD
  - STONE_SWORD
  - IRON_SWORD
  - GOLD_SWORD
  - DIAMOND_SWORD
  - WOOD_PICKAXE
  - STONE_PICKAXE
  - IRON_PICKAXE
  - GOLD_PICKAXE
  - DIAMOND_PICKAXE
  - WOOD_AXE
  - STONE_AXE
  - IRON_AXE
  - GOLD_AXE
  - DIAMOND_AXE
  - WOOD_SPADE
  - STONE_SPADE
  - IRON_SPADE
  - GOLD_SPADE
  - DIAMOND_SPADE
  - WOOD_HOE
  - STONE_HOE
  - IRON_HOE
  - GOLD_HOE
  - DIAMOND_HOE
  - X5588:HEAVY_DUTY_AXE
  - X5590:HEAVY_DUTY_PICKAXE
  - X5591:HEAVY_DUTY_SPADE
  - X5592:HEAVY_DUTY_SWORD
  - X5760:QUARTZ_AXE
  - X5591:QUARTZ_HOE
  - X5763:QUARTZ_PICKAXE
  - X5591:QUARTZ_SPADE
  - X5765:QUARTZ_SWORD
  - X9353:RUBY_AXE
  - X9356:RUBY_HOE
  - X9354:SAPPHIRE_AXE
  - X9355:PERIDOT_AXE
  - X9358:PERIDOT_HOE
  - X9359:RUBY_PICKAXE
  - X9360:SAPPHIRE_PICKAXE
  - X9361:PERIDOT_PICKAXE
  - X9362:RUBY_SPADE
  - X9363:SAPPHIRE_SPADE
  - X9364:PERIDOT_SPADE
  - X9365:RUBY_SWORD
  - X9366:SAPPHIRE_SWORD
  - X9368:PERIDOT_SWORD
  - X9381:RUBY_SICKLE
  - X9382:SAPPHIRE_SICKLE
  - X9383:PERIDOT_SICKLE
  - X10163:DESH_SWORD
  - X10164:DESH_PICKAXE
  - X10165:DESH_SPADE
  - X10166:DESH_HOE
  - X10167:DESH_AXE
  - X10261:ETHERIC_SWORD
  - X11776:WOODEN_SPEAR
  - X11777:STONE_SPEAR
  - X11778:IRON_SPEAR
  - X11779:DIAMOND_SPEAR
  - X11780:GOLDEN_SPEAR
  - X11781:WOODEN_HALBERD
  - X11782:STONE_HALBERD
  - X11783:IRON_HALBERD
  - X11784:DIAMOND_HALBERD
  - X11785:GOLDEN_HALBERD
  - X11786:WOODEN_BATTLEAXE
  - X11787:STONE_BATTLEAXE
  - X11788:IRON_BATTLEAXE
  - X11789:DIAMOND_BATTLEAXE
  - X11790:GOLDEN_BATTLEAXE
  - X11791:WOODEN_WARHAMMER
  - X11792:STONE_WARHAMMER
  - X11793:IRON_WARHAMMER
  - X11794:DIAMOND_WARHAMMER
  - X11795:GOLDEN_WARHAMMER
  - X11796:WOODEN_KNIFE
  - X11797:STONE_KNIFE
  - X11798:IRON_KNIFE
  - X11799:DIAMOND_KNIFE
  - X11800:GOLDEN_KNIFE
  - X11801:WOODEN_FLAIL
  - X11802:STONE_FLAIL
  - X11803:IRON_FLAIL
  - X11804:DIAMOND_FLAIL
  - X11805:GOLDEN_FLAIL
  - X11806:JAVELIN
  - X11819:CROSSBOW
  - X11824:WOODEN_BOOMERANG
  - X11825:STONE_BOOMERANG
  - X11826:IRON_BOOMERANG
  - X11827:DIAMOND_BOOMERANG
  - X11828:GOLDEN_BOOMERANG
  - X11834:WOODEN_KATANA
  - X11835:STONE_KATANA
  - X11836:IRON_KATANA
  - X11837:DIAMOND_KATANA
  - X11838:GOLDEN_KATANA
  - X20259:INVAR_SWORD
  - X20260:INVAR_SPADE
  - X20261:INVAR_PICKAXE
  - X20262:INVAR_AXE
  - X20263:INVAR_HOE
  - X20264:INVAR_SHEARS
  - X20264:INVAR_FISHING_ROD
  - X20264:INVAR_SICKLE
  - X20267:INVAR_BATTLEWRENCH
  - X20759:INVAR_SWORD
  armour:
    helmet:
    - LEATHER_HELMET
    - STONE_HELMET
    - CHAINMAIL_HELMET
    - IRON_HELMET
    - GOLD_HELMET
    - DIAMOND_HELMET
    - SKULL_ITEM
    - X5561:HEAVY_DUTY_HELMET
    - X8893:INVAR_HELMET
    - X10168:DESH_HELMET
    - X20413:HAZMAT_HELMET
    - X25027:POWER_ARMOUR_HELMET
    chest:
    - LEATHER_CHESTPLATE
    - STONE_CHESTPLATE
    - CHAINMAIL_CHESTPLATE
    - IRON_CHESTPLATE
    - GOLD_CHESTPLATE
    - DIAMOND_CHESTPLATE
    - X5560:HEAVY_DUTY_CHESTPLATE
    - X8891:INVAR_CHESTPLATE
    - X10169:DESH_CHESTPLATE
    - X20410:HAZMAT_CHESTPLATE
    - X25028:POWER_ARMOUR_CHESTPLATE
    legs:
    - LEATHER_LEGGINGS
    - STONE_LEGGINGS
    - CHAINMAIL_LEGGINGS
    - IRON_LEGGINGS
    - GOLD_LEGGINGS
    - DIAMOND_LEGGINGS
    - X5562:HEAVY_DUTY_LEGGINGS
    - X8892:INVAR_LEGGINGS
    - X10170:DESH_LEGGINGS
    - X20412:HAZMAT_LEGGINGS
    - X25029:POWER_ARMOUR_LEGGINGS
    boots:
    - LEATHER_BOOTS
    - STONE_BOOTS
    - CHAINMAIL_BOOTS
    - IRON_BOOTS
    - GOLD_BOOTS
    - DIAMOND_BOOTS
    - X5559:HEAVY_DUTY_BOOTS
    - X8894:INVAR_BOOTS
    - X10171:DESH_BOOTS
    - X12306:PLASTIC_BOOTS
    - X20411:HAZMAT_BOOTS
    - X25030:POWER_ARMOUR_BOOTS
npcModifier:
  worldNEW:
    healthMultiplier: 0.0
    damageMultiplier: 0.0
    expMultiplier: 0.0
    location:
      x: 0
      y: 65
      z: 0
  worldNEW_NETHER:
    healthMultiplier: 0.055
    damageMultiplier: 0.0045
    expMultiplier: 0.0045
    location:
      x: 0
      y: 65
      z: 0
healthPerLevel: 6
durabilityLoss:
  enchant:
    unbreakingLevelMultiplier: 33
