Sign_Money: true
Money: 100
Sign_Item: false
Item:
  Material: 1
  Amount: 1
Time: 10
###############################
#  作者:syx330679663--MCBBS   
#  希望能得到你宝贵的建议                
#  QQ或者站内信均可，小弟拜谢      
###############################