
# 是否开启强化成功全服公告
broadcast: true
# 默认强化成功几率
Percent: 10
# 可强化的物品
items:
  # 格式：物品ID|附魔ID
  # 例：石头强化加锋利附魔：1|16
  # 附魔ID参考：http://minecraft-zh.gamepedia.com/%E9%99%84%E9%AD%94#.E9.AD.94.E5.92.92
  - '276|16'

# 强化石
qhs:
  fjqh:
    # 物品ID
    id: 265
    # 名字
    Name: '&a&l凡级强化石'
    # Lore
    Lore:
    - '&a&l【功能】'
    - '&5可强化指定装备/提升装备等级'
    - '&2成功率25%&4[失败可能爆装备]'
    - '&a&l【用法】'
    - '&6输入/qh 即可打开强化界面'
    - '&a【兑换介绍】'
    - '&9可前往轻语城大厅找强化兑换使兑换高级的强化石'
    - '&a【爆装介绍】'
    - '&6[0-20级10%爆][20-40级20%爆][40-70级30%爆][70-*级40%爆]'
    - '&a装备等级越高，建议使用成功率越高的强化石避免爆装'
    # 增加的成功率，0为0%,100为100%
    Percent: 15
    # 强化石的有效等级
    # 格式：最小等级-最大等级
    # 最大等级填*为无限大
    Vaild: '0-*'

  bjqh:
    # 物品ID
    id: 265
    # 名字
    Name: '&b&l宝级强化石'
    # Lore
    Lore:
    - '&a&l【功能】'
    - '&5可强化指定装备/提升装备等级'
    - '&2成功率45%&4[失败可能爆装备]'
    - '&a&l【用法】'
    - '&6输入/qh 即可打开强化界面'
    - '&a【兑换介绍】'
    - '&9可前往轻语城大厅找强化兑换使兑换高级的强化石'
    - '&a【爆装介绍】'
    - '&6[0-20级10%爆][20-40级20%爆][40-70级30%爆][70-*级40%爆]'
    - '&a装备等级越高，建议使用成功率越高的强化石避免爆装'
    # 增加的成功率，0为0%,100为100%
    Percent: 35
    # 强化石的有效等级
    # 格式：最小等级-最大等级
    # 最大等级填*为无限大
    Vaild: '0-*'

  ljqh:
    # 物品ID
    id: 265
    # 名字
    Name: '&6&l灵级强化石'
    # Lore
    Lore:
    - '&a&l【功能】'
    - '&5可强化指定装备/提升装备等级'
    - '&2成功率55%&4[失败可能爆装备]'
    - '&a&l【用法】'
    - '&6输入/qh 即可打开强化界面'
    - '&a【兑换介绍】'
    - '&9可前往轻语城大厅找强化兑换使兑换高级的强化石'
    - '&a【爆装介绍】'
    - '&6[0-20级10%爆][20-40级20%爆][40-70级30%爆][70-*级40%爆]'
    - '&a装备等级越高，建议使用成功率越高的强化石避免爆装'
    # 增加的成功率，0为0%,100为100%
    Percent: 40
    # 强化石的有效等级
    # 格式：最小等级-最大等级
    # 最大等级填*为无限大
    Vaild: '0-*'

  xjqh:
    # 物品ID
    id: 265
    # 名字
    Name: '&5&l仙级级强化石'
    # Lore
    Lore:
    - '&a&l【功能】'
    - '&5可强化指定装备/提升装备等级'
    - '&2成功率75%&4[失败可能爆装备]'
    - '&a&l【用法】'
    - '&6输入/qh 即可打开强化界面'
    - '&a【兑换介绍】'
    - '&9可前往轻语城大厅找强化兑换使兑换高级的强化石'
    - '&a【爆装介绍】'
    - '&6[0-20级10%爆][20-40级20%爆][40-70级30%爆][70-*级40%爆]'
    - '&a装备等级越高，建议使用成功率越高的强化石避免爆装'
    - '&a【点券购买：5点券】'
    # 增加的成功率，0为0%,100为100%
    Percent: 60
    # 强化石的有效等级
    # 格式：最小等级-最大等级
    # 最大等级填*为无限大
    Vaild: '0-*'

  sjqh:
    # 物品ID
    id: 265
    # 名字
    Name: '&6&l圣级强化石'
    # Lore
    Lore:
    - '&a&l【功能】'
    - '&5可强化指定装备/提升装备等级'
    - '&2成功率100%&4[防爆]'
    - '&a&l【用法】'
    - '&6输入/qh 即可打开强化界面'
    - '&a【兑换介绍】'
    - '&9可前往轻语城大厅到强化兑换使兑换高级的强化石'
    - '&a【爆装介绍】'
    - '&6[0-20级10%爆][20-40级20%爆][40-70级30%爆][70-*级40%爆]'
    - '&a装备等级越高，建议使用成功率越高的强化石避免爆装'
    - '&a【点券购买：10点券】'
    # 增加的成功率，0为0%,100为100%
    Percent: 90
    # 强化石的有效等级
    # 格式：最小等级-最大等级
    # 最大等级填*为无限大
    Vaild: '0-*'

# 强化失败时爆装备几率
boom:
  # 格式：最小等级|最大等级|几率
  # 例：0到10级50%爆装备：0|10|50
  # 最大等级填*为无限大
  # 未定义的等级则不会爆
  - '0|20|10'
  - '20|40|20'
  - '40|70|30'
  - '70|200|40'

# 强化信息
info:
  # 显示在物品名后面的信息，{lvl}为强化等级
  name: '&5&l+{lvl} 级'
  # 显示在Lore第一行的信息，{lvl}为强化等级
  lore: '&6&l强化等级：{lvl}'