#Main configuration

disabled-worlds:
  - world_nether
  - city

#This will not count vanished players in the online value
hide-vanished: false

Scoreboard:
  Title: '&6&l--->-MC物语-群组服<---'
  #seconds
  # For instant updates you can or 1 and it will update every second
  Update-delay: 2
  Items:
    #The Title must have under 16 characters
    #Title: Type
    '&d&l玩家人数': '%online%'
    '&b&l现金数量': '%money%'
    '&e&l升级经验': '%xp_to_level%'
    '&4&l在线时间': '%lifetime%'
    '&e&l目前经验': '%exp%'
    '&d&l腐竹Q1406845568': '%max_player%'
    '&4Q群&a[ARROW2]422129912': '%ping%'

#Let ScoreboardStats track stats (kills, deaths, mobkills, killstreak) You need no plugin for this
enable-pvpstats: false

#In minutes
PvPStats-SaveIntervall: 15

Temp-Scoreboard-enabled: false

Temp-Scoreboard:
  Title: '&a&lTop Kills'
  #%mob% | %kills% | %killstreak%
  Type: '%kills%'
  Color: '&9'
  #How many Players would be displayed
  Items: 5
  Intervall-show: 300
  Intervall-disappear: 300

pluginUpdate: true